name: deploy test

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: fangbinwei/aliyun-oss-website-action@3993bfd
      with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: "fangbinwei-blog"
          endpoint: "oss-cn-shanghai.aliyuncs.com"
          folder: "example/"

